site_name: 严旭铧的简历
nav: 
  - 主页: index.md
  - 核心项目:
      - 心电监测设备: project1_ecg.md
      - 风电功率超短期多步时序预测: project2_wind.md
      - 仿真实验平台: project3_simulation.md
  - 学生工作: student_work.md
docs_dir: notes
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: LXGW WenKai
    code: JetBrains Mono
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - codehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js